[tool.poetry]
name = "nepal-entity-service-fastapi"
version = "2.0.0"
description = "🇳🇵 Open Source, open data, and open API for managing Nepali public entities with FastAPI and PostgreSQL"
authors = ["NewNepal Contributors"]
license = "Hippocratic-3.0"
readme = "README.md"

packages = [
    { include = "src" }
]

# Other sections remain unchanged
